openapi: "3.0.3"
info:
  title: "CarRentalShop API"
  description: "CarRentalShop API"
  version: "1.0.0"
servers:
  - url: "https://CarRentalShop"
paths:
  /api/rentals:
    get:
      summary: "GET api/rentals"
      operationId: "getAllRentals"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/RentalDTO"
    post:
      summary: "POST api/rentals"
      operationId: "createRental"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RentalDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RentalDTO"
  /api/rentals/{id}:
    get:
      summary: "GET api/rentals/{id}"
      operationId: "getRentalById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RentalDTO"
    put:
      summary: "PUT api/rentals/{id}"
      operationId: "updateRental"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RentalDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RentalDTO"
    delete:
      summary: "DELETE api/rentals/{id}"
      operationId: "deleteRental"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
  /api/rentals/user/{userId}:
    get:
      summary: "GET api/rentals/user/{userId}"
      operationId: "getRentalsByUser"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/RentalDTO"
  /api/rentals/car/{carId}:
    get:
      summary: "GET api/rentals/car/{carId}"
      operationId: "getRentalsByCar"
      parameters:
        - name: "carId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/RentalDTO"
components:
  schemas:
    RoleDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        roleName:
          type: "string"
    UserDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        username:
          type: "string"
        name:
          type: "string"
        surname:
          type: "string"
        contactInfo:
          type: "string"
        password:
          type: "string"
        role:
          $ref: "#/components/schemas/RoleDTO"
        rentals:
          type: "array"
          items:
            $ref: "#/components/schemas/RentalDTO"
    BigDecimal:
      type: "object"
      properties: { }
    CarDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        make:
          type: "string"
        model:
          type: "string"
        year:
          type: "integer"
          format: "int32"
        registrationNumber:
          type: "string"
        rentalPrice:
          $ref: "#/components/schemas/BigDecimal"
    RentalDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        user:
          $ref: "#/components/schemas/UserDTO"
        car:
          $ref: "#/components/schemas/CarDTO"
        startDate:
          type: "string"
          format: "date"
        endDate:
          type: "string"
          format: "date"
        isPaid:
          type: "boolean"
        totalPrice:
          $ref: "#/components/schemas/BigDecimal"
    Void:
      type: "object"
      properties: { }